name: 'GitHub Action for creating a GitHub Release'
description: 'This is a GitHub Action for creating a GitHub Release.'

branding:
  icon: upload
  color: 'blue'

inputs:
  owner:
    description: 'The owner of github'
    required: false
  repo:
    description: 'The repo of github'
    required: false
  release_name:
    description: 'The release name of github'
    required: false
  tag_name:
    description: 'The tag name of github'
    required: false
  body:
    description: 'Content of the release'
    required: false
  body_path:
    description: 'Content path of the release'
    required: false
  draft:
    description: 'Draft release option'
    required: false
    default: 'false'
  prerelease:
    description: 'Prerelease option'
    required: false
    default: 'false'

outputs:
  id:
    description: 'The id of the created release'
  html_url:
    description: 'The url to view the release'
  upload_url:
    description: 'The url for uploading assets to the release'

runs:
  using: 'node16'
  main: 'dist/index.js'
